### ISSUE TITLE
Gathering facts before bootstrap playbook has run on all nodes leads to: import docker ModuleNotFoundError: No module named 'docker'

### ISSUE THREAD

**Issue by grawert** [osism/ansible-playbooks#222]
```
osism-generic operator -l 'all:!manager' -u ubuntu

PLAY [Make ssh pipelining working] ************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************************
[WARNING]: Failure executing fact script (/etc/ansible/facts.d/docker_containers.fact), rc: 1, err: Traceback (most recent call last):   File "/etc/ansible/facts.d/docker_containers.fact", line 6, in
<module>     import docker ModuleNotFoundError: No module named 'docker'
[WARNING]: Failure executing fact script (/etc/ansible/facts.d/docker_images.fact), rc: 1, err: Traceback (most recent call last):   File "/etc/ansible/facts.d/docker_images.fact", line 6, in <module>
import docker ModuleNotFoundError: No module named 'docker'
```

**Comment by berendt** [comment]
The problem is that with osism.commons.facts facts are rolled out for Docker by default and the necessary dependencies are only installed with osism.services.docker.
